[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:uvicorn]
command=python3 -m uvicorn app.main:app --host 0.0.0.0 --port 8765 --log-level %(ENV_LOG_LEVEL)s
directory=/
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
