name: "Crater"
description: "Embedded Invoicing & Bill Pay for platforms. Add payments, invoicing workflows, and working capital tools for users."
version: "0.0.2"
slug: "crater"
init: false
arch:
  - amd64

startup: services
ports:
  80/tcp: 7649
